## The Facenet Library
* The case of face detection using Facenet library's models is an interesting case. We don't have to train anything or worry about models or hyperparameters. We simply generate embeddings.
* Embeddings are generating using Facenet's CNN models that is for detedting fac

In [11]:
import os
from PIL import Image
import torch
from facenet_pytorch import MTCNN, InceptionResnetV1
from scipy.spatial.distance import cosine

# Initialize MTCNN and InceptionResnetV1
mtcnn = MTCNN(image_size=160, margin=20)
model = InceptionResnetV1(pretrained='vggface2').eval()


In [3]:

# Path to the dataset containing folders of individuals (for known faces)
dataset_path = "./faces/"  # Replace with your dataset path

# Threshold for similarity matching
threshold = 0.6

# Step 1: Generate embeddings for known faces

known_embeddings = {}

for person_name in os.listdir(dataset_path):
    print(person_name)
    person_folder = os.path.join(dataset_path, person_name)
    
    if os.path.isdir(person_folder):
        for image_name in os.listdir(person_folder):
            print(image_name)
            image_path = os.path.join(person_folder, image_name)
            try:
                # Load image and process with MTCNN
                print(image_path)
                image = Image.open(image_path)
                cropped_face = mtcnn(image)

                if cropped_face is not None:
                    # Generate 128D embeddings for the face
                    print(cropped_face)
                    embedding = model(cropped_face.unsqueeze(0))
                    known_embeddings[person_name] = embedding.detach()
                    break  # Only use one image per person
            except Exception as e:
                print(f"Error processing {image_path}: {e}")

    




Abdullah_Gul
Abdullah_Gul_0001.jpg
./faces/Abdullah_Gul\Abdullah_Gul_0001.jpg
tensor([[[ 0.9102,  0.9102,  0.9102,  ..., -0.5898, -0.5664, -0.5430],
         [ 0.9102,  0.9102,  0.9102,  ..., -0.5508, -0.5117, -0.4883],
         [ 0.9102,  0.9102,  0.9102,  ..., -0.4570, -0.4258, -0.4102],
         ...,
         [-0.5820, -0.5820, -0.5898,  ..., -0.7227, -0.6758, -0.6367],
         [-0.5664, -0.5664, -0.5742,  ..., -0.7461, -0.6992, -0.6445],
         [-0.5586, -0.5586, -0.5664,  ..., -0.7695, -0.7070, -0.6523]],

        [[ 0.9258,  0.9258,  0.9258,  ..., -0.7383, -0.7070, -0.6836],
         [ 0.9258,  0.9258,  0.9258,  ..., -0.6992, -0.6602, -0.6367],
         [ 0.9258,  0.9258,  0.9258,  ..., -0.6055, -0.5742, -0.5586],
         ...,
         [-0.6055, -0.6055, -0.6055,  ..., -0.7070, -0.6602, -0.6289],
         [-0.5898, -0.5898, -0.5977,  ..., -0.7227, -0.6758, -0.6211],
         [-0.5820, -0.5820, -0.5898,  ..., -0.7461, -0.6836, -0.6289]],

        [[ 0.8242,  0.8242,  0.8242,  

Andy_Roddick
Andy_Roddick_0001.jpg
./faces/Andy_Roddick\Andy_Roddick_0001.jpg
tensor([[[ 0.7461,  0.7539,  0.7773,  ...,  0.9414,  0.9336,  0.9258],
         [ 0.7461,  0.7539,  0.7773,  ...,  0.9414,  0.9336,  0.9336],
         [ 0.7539,  0.7617,  0.7852,  ...,  0.9492,  0.9414,  0.9414],
         ...,
         [-0.0820, -0.0820, -0.0742,  ..., -0.2383, -0.2617, -0.2695],
         [-0.0586, -0.0586, -0.0508,  ..., -0.3477, -0.4102, -0.4336],
         [-0.0430, -0.0430, -0.0352,  ..., -0.4258, -0.5039, -0.5430]],

        [[ 0.7852,  0.7930,  0.8164,  ...,  0.9023,  0.8945,  0.8867],
         [ 0.7852,  0.7930,  0.8164,  ...,  0.9023,  0.8945,  0.8945],
         [ 0.7930,  0.8008,  0.8242,  ...,  0.9102,  0.9023,  0.9023],
         ...,
         [-0.3398, -0.3398, -0.3320,  ..., -0.4336, -0.4414, -0.4492],
         [-0.3164, -0.3164, -0.3086,  ..., -0.5430, -0.5898, -0.6133],
         [-0.3008, -0.3008, -0.2930,  ..., -0.6211, -0.6914, -0.7227]],

        [[ 0.7383,  0.7461,  0.7695,  

Arnold_Schwarzenegger
Arnold_Schwarzenegger_0001.jpg
./faces/Arnold_Schwarzenegger\Arnold_Schwarzenegger_0001.jpg
tensor([[[-0.7070, -0.6914, -0.6602,  ..., -0.6211, -0.6445, -0.6602],
         [-0.6523, -0.6367, -0.6133,  ..., -0.6055, -0.6367, -0.6602],
         [-0.6289, -0.6211, -0.6055,  ..., -0.5898, -0.6367, -0.6602],
         ...,
         [-0.3789, -0.3945, -0.4258,  ...,  0.0898,  0.0977,  0.1055],
         [-0.2461, -0.2695, -0.3008,  ...,  0.1055,  0.0898,  0.0820],
         [-0.1680, -0.1992, -0.2461,  ...,  0.0117, -0.0039, -0.0117]],

        [[-0.7930, -0.7695, -0.7383,  ..., -0.6211, -0.6445, -0.6602],
         [-0.7305, -0.7148, -0.6914,  ..., -0.6055, -0.6367, -0.6602],
         [-0.7070, -0.6992, -0.6836,  ..., -0.6133, -0.6602, -0.6836],
         ...,
         [-0.4961, -0.5195, -0.5664,  ...,  0.1055,  0.1133,  0.1211],
         [-0.3633, -0.3945, -0.4414,  ...,  0.1289,  0.1055,  0.0977],
         [-0.2852, -0.3164, -0.3633,  ...,  0.0352,  0.0195,  0.0117]],

  

Britney_Spears
Britney_Spears_0001.jpg
./faces/Britney_Spears\Britney_Spears_0001.jpg
tensor([[[ 0.3086,  0.3164,  0.3242,  ..., -0.0586, -0.0430, -0.0273],
         [ 0.3242,  0.3320,  0.3477,  ..., -0.0508, -0.0430, -0.0430],
         [ 0.3320,  0.3477,  0.3789,  ..., -0.0586, -0.0508, -0.0508],
         ...,
         [ 0.4805,  0.4727,  0.4492,  ...,  0.2305,  0.1836,  0.1445],
         [ 0.4805,  0.4805,  0.4805,  ...,  0.1836,  0.1445,  0.1133],
         [ 0.4883,  0.4883,  0.4883,  ...,  0.1055,  0.0664,  0.0352]],

        [[ 0.0039,  0.0117,  0.0195,  ..., -0.2852, -0.2773, -0.2695],
         [ 0.0195,  0.0273,  0.0430,  ..., -0.2773, -0.2852, -0.2852],
         [ 0.0430,  0.0586,  0.0820,  ..., -0.2852, -0.2930, -0.2930],
         ...,
         [ 0.2617,  0.2383,  0.2070,  ..., -0.2070, -0.2227, -0.2383],
         [ 0.2617,  0.2539,  0.2383,  ..., -0.2539, -0.2617, -0.2695],
         [ 0.2695,  0.2617,  0.2461,  ..., -0.3320, -0.3398, -0.3477]],

        [[-0.4414, -0.4336, -0

Condoleezza_Rice
Condoleezza_Rice_0001.jpg
./faces/Condoleezza_Rice\Condoleezza_Rice_0001.jpg
tensor([[[-0.6992, -0.7070, -0.7148,  ..., -0.5898, -0.5586, -0.5352],
         [-0.6914, -0.7070, -0.7227,  ..., -0.6133, -0.5898, -0.5820],
         [-0.7148, -0.7227, -0.7305,  ..., -0.5742, -0.5820, -0.5898],
         ...,
         [-0.8008, -0.8008, -0.8008,  ..., -0.7227, -0.7148, -0.7148],
         [-0.7852, -0.7852, -0.7852,  ..., -0.7227, -0.7148, -0.7148],
         [-0.7773, -0.7773, -0.7773,  ..., -0.7305, -0.7227, -0.7227]],

        [[-0.7617, -0.7695, -0.7773,  ..., -0.6289, -0.5977, -0.5742],
         [-0.7539, -0.7617, -0.7695,  ..., -0.6523, -0.6289, -0.6211],
         [-0.7617, -0.7617, -0.7695,  ..., -0.6133, -0.6211, -0.6289],
         ...,
         [-0.7852, -0.7852, -0.7852,  ..., -0.7148, -0.7070, -0.7070],
         [-0.7695, -0.7695, -0.7695,  ..., -0.7148, -0.7070, -0.7070],
         [-0.7617, -0.7617, -0.7617,  ..., -0.7227, -0.7148, -0.7148]],

        [[-0.7773, -0.

Edmund_Stoiber
Edmund_Stoiber_0001.jpg
./faces/Edmund_Stoiber\Edmund_Stoiber_0001.jpg
tensor([[[-0.0430, -0.0352, -0.0117,  ...,  0.4727,  0.3867,  0.3242],
         [-0.0430, -0.0352, -0.0195,  ...,  0.5586,  0.4727,  0.4023],
         [-0.0352, -0.0273, -0.0195,  ...,  0.6445,  0.5664,  0.5039],
         ...,
         [ 0.0352,  0.0508,  0.0742,  ..., -0.1758, -0.2148, -0.2539],
         [ 0.0352,  0.0508,  0.0742,  ..., -0.1211, -0.1758, -0.2305],
         [ 0.0430,  0.0586,  0.0742,  ..., -0.0898, -0.1523, -0.2070]],

        [[ 0.3477,  0.3477,  0.3555,  ...,  0.3320,  0.2539,  0.1992],
         [ 0.3477,  0.3477,  0.3477,  ...,  0.4180,  0.3320,  0.2617],
         [ 0.3555,  0.3555,  0.3477,  ...,  0.4961,  0.4258,  0.3633],
         ...,
         [ 0.2070,  0.2227,  0.2461,  ..., -0.3242, -0.3633, -0.4023],
         [ 0.2227,  0.2383,  0.2539,  ..., -0.2852, -0.3398, -0.3945],
         [ 0.2383,  0.2539,  0.2695,  ..., -0.2695, -0.3164, -0.3633]],

        [[ 0.7305,  0.7305,  0

Gerhard_Schroeder
Gerhard_Schroeder_0001.jpg
./faces/Gerhard_Schroeder\Gerhard_Schroeder_0001.jpg
tensor([[[ 0.0664, -0.0898, -0.3320,  ..., -0.7227, -0.7227, -0.7227],
         [ 0.0977, -0.0820, -0.3477,  ..., -0.6211, -0.6367, -0.6445],
         [ 0.0117, -0.1523, -0.4180,  ..., -0.5742, -0.5898, -0.6055],
         ...,
         [-0.0977, -0.1055, -0.1211,  ...,  0.9727,  0.9727,  0.9727],
         [-0.1055, -0.1133, -0.1289,  ...,  0.9883,  0.9805,  0.9883],
         [-0.0820, -0.0898, -0.0977,  ...,  0.9648,  0.9727,  0.9805]],

        [[ 0.3633,  0.1992, -0.0508,  ..., -0.7617, -0.7617, -0.7617],
         [ 0.3867,  0.2070, -0.0664,  ..., -0.6602, -0.6758, -0.6836],
         [ 0.2930,  0.1211, -0.1445,  ..., -0.6289, -0.6445, -0.6602],
         ...,
         [ 0.4023,  0.3945,  0.3789,  ...,  0.8398,  0.8477,  0.8555],
         [ 0.3945,  0.3867,  0.3711,  ...,  0.8789,  0.8867,  0.8945],
         [ 0.4180,  0.4102,  0.4023,  ...,  0.8945,  0.9023,  0.9102]],

        [[ 0.5117,

Halle_Berry
Halle_Berry_0001.jpg
./faces/Halle_Berry\Halle_Berry_0001.jpg
tensor([[[-0.8242, -0.7930, -0.7383,  ..., -0.4492, -0.4492, -0.4492],
         [-0.8320, -0.8008, -0.7461,  ..., -0.3867, -0.3867, -0.3789],
         [-0.8320, -0.8008, -0.7617,  ..., -0.3320, -0.3164, -0.3086],
         ...,
         [ 0.0977,  0.0977,  0.0977,  ..., -0.1758, -0.2070, -0.2305],
         [ 0.0977,  0.0977,  0.0977,  ..., -0.2695, -0.3086, -0.3320],
         [ 0.0977,  0.0977,  0.1055,  ..., -0.3398, -0.3867, -0.4180]],

        [[-0.8242, -0.7930, -0.7383,  ..., -0.4883, -0.4883, -0.4883],
         [-0.8320, -0.8008, -0.7461,  ..., -0.4258, -0.4258, -0.4180],
         [-0.8320, -0.8008, -0.7617,  ..., -0.3711, -0.3555, -0.3477],
         ...,
         [-0.1523, -0.1523, -0.1523,  ..., -0.2773, -0.3086, -0.3242],
         [-0.1523, -0.1523, -0.1523,  ..., -0.3633, -0.3945, -0.4258],
         [-0.1523, -0.1523, -0.1445,  ..., -0.4258, -0.4727, -0.5039]],

        [[-0.8242, -0.7930, -0.7383,  ...,

Hugo_Chavez
Hugo_Chavez_0001.jpg
./faces/Hugo_Chavez\Hugo_Chavez_0001.jpg
tensor([[[-0.4805, -0.4961, -0.5117,  ..., -0.3164, -0.3164, -0.3164],
         [-0.4727, -0.4883, -0.5039,  ..., -0.3242, -0.3242, -0.3242],
         [-0.4570, -0.4805, -0.5039,  ..., -0.3477, -0.3320, -0.3320],
         ...,
         [ 0.3398,  0.3164,  0.2852,  ..., -0.3008, -0.2930, -0.2852],
         [ 0.3086,  0.2930,  0.2617,  ..., -0.3008, -0.2852, -0.2773],
         [ 0.2773,  0.2617,  0.2461,  ..., -0.3008, -0.2852, -0.2773]],

        [[-0.5430, -0.5586, -0.5742,  ..., -0.3008, -0.3008, -0.3008],
         [-0.5352, -0.5508, -0.5664,  ..., -0.3086, -0.3086, -0.3086],
         [-0.5195, -0.5430, -0.5664,  ..., -0.3320, -0.3164, -0.3164],
         ...,
         [ 0.2383,  0.2148,  0.1836,  ..., -0.3008, -0.2930, -0.2852],
         [ 0.2070,  0.1914,  0.1602,  ..., -0.3008, -0.2852, -0.2773],
         [ 0.1680,  0.1602,  0.1445,  ..., -0.3008, -0.2852, -0.2773]],

        [[-0.6289, -0.6445, -0.6602,  ...,

Jacques_Chirac
Jacques_Chirac_0001.jpg
./faces/Jacques_Chirac\Jacques_Chirac_0001.jpg
tensor([[[-0.6523, -0.6445, -0.6367,  ...,  0.7461,  0.7383,  0.7305],
         [-0.6055, -0.5977, -0.5898,  ...,  0.7539,  0.7461,  0.7383],
         [-0.5508, -0.5430, -0.5352,  ...,  0.7695,  0.7617,  0.7539],
         ...,
         [-0.7852, -0.8008, -0.8164,  ..., -0.2852, -0.2383, -0.2148],
         [-0.7617, -0.7695, -0.7773,  ..., -0.2930, -0.2539, -0.2305],
         [-0.7461, -0.7539, -0.7617,  ..., -0.3008, -0.2617, -0.2383]],

        [[-0.4414, -0.4336, -0.4258,  ...,  0.6211,  0.6133,  0.6055],
         [-0.3945, -0.3867, -0.3789,  ...,  0.6289,  0.6211,  0.6133],
         [-0.3398, -0.3320, -0.3242,  ...,  0.6445,  0.6367,  0.6289],
         ...,
         [-0.7070, -0.7227, -0.7383,  ..., -0.1602, -0.1289, -0.1055],
         [-0.7305, -0.7383, -0.7461,  ..., -0.1758, -0.1445, -0.1211],
         [-0.7383, -0.7461, -0.7539,  ..., -0.1914, -0.1523, -0.1289]],

        [[-0.8398, -0.8398, -0

Jean_Charest
Jean_Charest_0002.jpg
./faces/Jean_Charest\Jean_Charest_0002.jpg
tensor([[[ 0.0508,  0.0352,  0.0117,  ...,  0.1992,  0.2070,  0.2070],
         [ 0.0195,  0.0117,  0.0039,  ...,  0.1992,  0.2070,  0.2070],
         [-0.0195, -0.0195, -0.0195,  ...,  0.1914,  0.1992,  0.1992],
         ...,
         [ 0.5430,  0.4570,  0.3242,  ...,  0.2930,  0.1367,  0.0430],
         [ 0.6680,  0.5820,  0.4414,  ...,  0.2461,  0.1055,  0.0195],
         [ 0.7305,  0.6445,  0.5039,  ...,  0.2070,  0.0664, -0.0273]],

        [[ 0.0273,  0.0117, -0.0117,  ...,  0.0820,  0.0977,  0.1055],
         [-0.0039, -0.0117, -0.0195,  ...,  0.0820,  0.0977,  0.1055],
         [-0.0430, -0.0430, -0.0430,  ...,  0.0742,  0.0820,  0.0898],
         ...,
         [ 0.4414,  0.3477,  0.2070,  ...,  0.3945,  0.2461,  0.1602],
         [ 0.5742,  0.4805,  0.3477,  ...,  0.3477,  0.2148,  0.1367],
         [ 0.6523,  0.5586,  0.4102,  ...,  0.3086,  0.1758,  0.0977]],

        [[-0.1055, -0.1211, -0.1445,  

Jennifer_Garner
Jennifer_Garner_0002.jpg
./faces/Jennifer_Garner\Jennifer_Garner_0002.jpg
tensor([[[-0.6523, -0.6133, -0.5430,  ..., -0.5742, -0.5820, -0.5898],
         [-0.5820, -0.5508, -0.5039,  ..., -0.5430, -0.5508, -0.5586],
         [-0.5273, -0.5039, -0.4727,  ..., -0.5117, -0.5195, -0.5273],
         ...,
         [-0.5195, -0.5195, -0.5117,  ..., -0.7852, -0.7695, -0.7617],
         [-0.4805, -0.4883, -0.4961,  ..., -0.7773, -0.7539, -0.7383],
         [-0.4727, -0.4805, -0.4883,  ..., -0.7773, -0.7539, -0.7383]],

        [[-0.8320, -0.7930, -0.7227,  ..., -0.7070, -0.7148, -0.7227],
         [-0.7617, -0.7305, -0.6836,  ..., -0.6758, -0.6836, -0.6914],
         [-0.7070, -0.6836, -0.6523,  ..., -0.6523, -0.6602, -0.6680],
         ...,
         [-0.7461, -0.7461, -0.7383,  ..., -0.8867, -0.8711, -0.8633],
         [-0.7070, -0.7148, -0.7227,  ..., -0.8867, -0.8633, -0.8477],
         [-0.6992, -0.7070, -0.7148,  ..., -0.8867, -0.8633, -0.8477]],

        [[-0.9414, -0.9023

John_Allen_Muhammad
John_Allen_Muhammad_0002.jpg
./faces/John_Allen_Muhammad\John_Allen_Muhammad_0002.jpg
tensor([[[-0.5352, -0.5508, -0.5664,  ..., -0.5664, -0.6992, -0.7852],
         [-0.5508, -0.5586, -0.5742,  ..., -0.5195, -0.6523, -0.7383],
         [-0.5664, -0.5742, -0.5742,  ..., -0.4492, -0.5977, -0.6914],
         ...,
         [-0.0898, -0.0898, -0.0820,  ...,  0.8477,  0.8398,  0.8320],
         [-0.0977, -0.0977, -0.0898,  ...,  0.8477,  0.8398,  0.8398],
         [-0.0977, -0.0977, -0.0977,  ...,  0.8555,  0.8477,  0.8477]],

        [[-0.5430, -0.5586, -0.5742,  ..., -0.6680, -0.7617, -0.8242],
         [-0.5586, -0.5664, -0.5820,  ..., -0.6211, -0.7148, -0.7773],
         [-0.5742, -0.5820, -0.5820,  ..., -0.5508, -0.6680, -0.7383],
         ...,
         [-0.2227, -0.2227, -0.2148,  ...,  0.9023,  0.9102,  0.9102],
         [-0.2227, -0.2227, -0.2148,  ...,  0.9102,  0.9180,  0.9180],
         [-0.2227, -0.2227, -0.2227,  ...,  0.9180,  0.9258,  0.9258]],

        [[

John_Paul_II
John_Paul_II_0001.jpg
./faces/John_Paul_II\John_Paul_II_0001.jpg
tensor([[[ 0.7383,  0.7617,  0.7773,  ...,  0.5117,  0.5195,  0.5273],
         [ 0.6992,  0.7305,  0.7539,  ...,  0.4961,  0.5039,  0.5117],
         [ 0.6445,  0.6836,  0.7305,  ...,  0.4961,  0.5039,  0.5117],
         ...,
         [ 0.6367,  0.6523,  0.6680,  ...,  0.7227,  0.7227,  0.7227],
         [ 0.6289,  0.6445,  0.6602,  ...,  0.7227,  0.7227,  0.7227],
         [ 0.6211,  0.6367,  0.6523,  ...,  0.7305,  0.7227,  0.7148]],

        [[ 0.2383,  0.2617,  0.2852,  ...,  0.3711,  0.3789,  0.3867],
         [ 0.2148,  0.2539,  0.2852,  ...,  0.3555,  0.3633,  0.3711],
         [ 0.2070,  0.2461,  0.2930,  ...,  0.3555,  0.3633,  0.3711],
         ...,
         [ 0.5898,  0.6055,  0.6211,  ...,  0.6680,  0.6680,  0.6680],
         [ 0.5820,  0.5977,  0.6133,  ...,  0.6680,  0.6680,  0.6680],
         [ 0.5742,  0.5898,  0.6055,  ...,  0.6758,  0.6680,  0.6602]],

        [[ 0.0273,  0.0508,  0.0820,  

Julie_Gerberding
Julie_Gerberding_0001.jpg
./faces/Julie_Gerberding\Julie_Gerberding_0001.jpg
tensor([[[-0.2383, -0.2383, -0.2461,  ...,  0.5586,  0.5508,  0.5508],
         [-0.2461, -0.2461, -0.2539,  ...,  0.5352,  0.5352,  0.5430],
         [-0.2461, -0.2539, -0.2617,  ...,  0.4961,  0.5195,  0.5352],
         ...,
         [-0.7461, -0.7461, -0.7539,  ..., -0.8477, -0.8555, -0.8555],
         [-0.7539, -0.7539, -0.7617,  ..., -0.8555, -0.8555, -0.8477],
         [-0.7695, -0.7695, -0.7773,  ..., -0.8633, -0.8477, -0.8398]],

        [[-0.2305, -0.2305, -0.2383,  ...,  0.5742,  0.5742,  0.5742],
         [-0.2383, -0.2383, -0.2461,  ...,  0.5508,  0.5586,  0.5664],
         [-0.2383, -0.2461, -0.2539,  ...,  0.5117,  0.5430,  0.5586],
         ...,
         [-0.8164, -0.8164, -0.8242,  ..., -0.8867, -0.8711, -0.8711],
         [-0.8242, -0.8242, -0.8320,  ..., -0.8867, -0.8711, -0.8633],
         [-0.8398, -0.8398, -0.8477,  ..., -0.8867, -0.8711, -0.8555]],

        [[-0.2695, -0.

Lance_Armstrong
Lance_Armstrong_0001.jpg
./faces/Lance_Armstrong\Lance_Armstrong_0001.jpg
tensor([[[-0.1289, -0.1211, -0.1133,  ..., -0.6523, -0.6445, -0.6367],
         [-0.1133, -0.1055, -0.0898,  ..., -0.6445, -0.6445, -0.6445],
         [-0.0742, -0.0664, -0.0586,  ..., -0.6367, -0.6445, -0.6445],
         ...,
         [ 0.5508,  0.5586,  0.5664,  ..., -0.3008, -0.3164, -0.3242],
         [ 0.5508,  0.5586,  0.5664,  ..., -0.3164, -0.3320, -0.3398],
         [ 0.5586,  0.5586,  0.5664,  ..., -0.3320, -0.3477, -0.3555]],

        [[-0.2227, -0.2148, -0.2070,  ..., -0.7305, -0.7227, -0.7227],
         [-0.2070, -0.1992, -0.1836,  ..., -0.7383, -0.7305, -0.7227],
         [-0.1758, -0.1680, -0.1602,  ..., -0.7305, -0.7305, -0.7227],
         ...,
         [ 0.5039,  0.5117,  0.5195,  ..., -0.3555, -0.3789, -0.3945],
         [ 0.5039,  0.5117,  0.5195,  ..., -0.3711, -0.3867, -0.3945],
         [ 0.5117,  0.5117,  0.5195,  ..., -0.3789, -0.3945, -0.4023]],

        [[-0.4258, -0.4180

Mahathir_Mohamad
Mahathir_Mohamad_0001.jpg
./faces/Mahathir_Mohamad\Mahathir_Mohamad_0001.jpg
tensor([[[-0.5039, -0.5195, -0.5430,  ..., -0.6289, -0.6367, -0.6445],
         [-0.4102, -0.4336, -0.4805,  ..., -0.6523, -0.6602, -0.6680],
         [-0.3945, -0.4180, -0.4570,  ..., -0.6367, -0.6445, -0.6523],
         ...,
         [ 0.9805,  0.9805,  0.9805,  ..., -0.7695, -0.7695, -0.7695],
         [ 0.9961,  0.9961,  0.9883,  ..., -0.7695, -0.7695, -0.7695],
         [ 0.9961,  0.9961,  0.9961,  ..., -0.7695, -0.7695, -0.7695]],

        [[-0.4727, -0.4883, -0.5117,  ..., -0.6758, -0.6680, -0.6680],
         [-0.3789, -0.4023, -0.4492,  ..., -0.6914, -0.6914, -0.6914],
         [-0.3633, -0.3867, -0.4258,  ..., -0.6758, -0.6836, -0.6836],
         ...,
         [ 0.9883,  0.9883,  0.9961,  ..., -0.7773, -0.7773, -0.7773],
         [ 0.9961,  0.9961,  0.9961,  ..., -0.7773, -0.7773, -0.7773],
         [ 0.9961,  0.9961,  0.9961,  ..., -0.7773, -0.7773, -0.7773]],

        [[-0.5820, -0.

Michael_Jackson
Michael_Jackson_0001.jpg
./faces/Michael_Jackson\Michael_Jackson_0001.jpg
tensor([[[-0.8555, -0.8477, -0.8398,  ..., -0.8320, -0.8320, -0.8320],
         [-0.8555, -0.8477, -0.8398,  ..., -0.8398, -0.8398, -0.8398],
         [-0.8633, -0.8477, -0.8320,  ..., -0.8477, -0.8477, -0.8477],
         ...,
         [-0.8242, -0.7930, -0.7461,  ..., -0.9570, -0.9492, -0.9492],
         [-0.8555, -0.8242, -0.7852,  ..., -0.9570, -0.9492, -0.9492],
         [-0.8867, -0.8633, -0.8242,  ..., -0.9492, -0.9414, -0.9414]],

        [[-0.8555, -0.8477, -0.8398,  ..., -0.9023, -0.9023, -0.9023],
         [-0.8555, -0.8477, -0.8398,  ..., -0.9102, -0.9102, -0.9102],
         [-0.8633, -0.8477, -0.8320,  ..., -0.9180, -0.9180, -0.9180],
         ...,
         [-0.8555, -0.8242, -0.7773,  ..., -0.9414, -0.9492, -0.9492],
         [-0.8789, -0.8555, -0.8086,  ..., -0.9414, -0.9492, -0.9492],
         [-0.8945, -0.8711, -0.8320,  ..., -0.9336, -0.9414, -0.9414]],

        [[-0.8555, -0.8477

Nancy_Pelosi
Nancy_Pelosi_0001.jpg
./faces/Nancy_Pelosi\Nancy_Pelosi_0001.jpg
tensor([[[-0.3477, -0.3555, -0.3789,  ..., -0.5742, -0.5664, -0.5664],
         [-0.3711, -0.3789, -0.3945,  ..., -0.5820, -0.5742, -0.5742],
         [-0.3867, -0.3867, -0.3945,  ..., -0.5898, -0.5820, -0.5820],
         ...,
         [-0.8711, -0.8711, -0.8711,  ...,  0.2695,  0.2617,  0.2617],
         [-0.8633, -0.8633, -0.8633,  ...,  0.2539,  0.2461,  0.2461],
         [-0.8398, -0.8398, -0.8477,  ...,  0.2461,  0.2383,  0.2383]],

        [[-0.4805, -0.4883, -0.5117,  ..., -0.6758, -0.6680, -0.6680],
         [-0.5039, -0.5117, -0.5273,  ..., -0.6836, -0.6758, -0.6758],
         [-0.5195, -0.5195, -0.5273,  ..., -0.6914, -0.6836, -0.6836],
         ...,
         [-0.8555, -0.8555, -0.8555,  ..., -0.1211, -0.1289, -0.1289],
         [-0.8477, -0.8477, -0.8477,  ..., -0.1367, -0.1445, -0.1445],
         [-0.8242, -0.8242, -0.8320,  ..., -0.1602, -0.1680, -0.1680]],

        [[-0.7148, -0.7227, -0.7461,  

Paradorn_Srichaphan
Paradorn_Srichaphan_0001.jpg
./faces/Paradorn_Srichaphan\Paradorn_Srichaphan_0001.jpg
tensor([[[-0.9727, -0.9648, -0.9414,  ...,  0.2383,  0.2461,  0.2461],
         [-0.9648, -0.9570, -0.9414,  ...,  0.2383,  0.2539,  0.2617],
         [-0.9805, -0.9727, -0.9648,  ...,  0.1836,  0.2227,  0.2461],
         ...,
         [ 0.4180,  0.3477,  0.2305,  ..., -0.1445, -0.1758, -0.1992],
         [ 0.4023,  0.3320,  0.2148,  ..., -0.1914, -0.2227, -0.2461],
         [ 0.3555,  0.2930,  0.1836,  ..., -0.2383, -0.2617, -0.2773]],

        [[-0.9492, -0.9336, -0.9180,  ...,  0.0430,  0.0508,  0.0508],
         [-0.9414, -0.9336, -0.9102,  ...,  0.0508,  0.0586,  0.0664],
         [-0.9570, -0.9492, -0.9336,  ...,  0.0117,  0.0352,  0.0586],
         ...,
         [ 0.2695,  0.1914,  0.0586,  ..., -0.0820, -0.1133, -0.1367],
         [ 0.2305,  0.1523,  0.0195,  ..., -0.1211, -0.1523, -0.1758],
         [ 0.1758,  0.0977, -0.0273,  ..., -0.1680, -0.1914, -0.2070]],

        [[

Pierce_Brosnan
Pierce_Brosnan_0001.jpg
./faces/Pierce_Brosnan\Pierce_Brosnan_0001.jpg
tensor([[[-0.2695, -0.3086, -0.3477,  ..., -0.6367, -0.7383, -0.8008],
         [-0.3008, -0.3711, -0.4570,  ..., -0.4883, -0.5117, -0.5352],
         [-0.4023, -0.4336, -0.4727,  ..., -0.4961, -0.4648, -0.4492],
         ...,
         [-0.1211, -0.0977, -0.0742,  ...,  0.6289,  0.6289,  0.6367],
         [-0.1133, -0.1055, -0.0898,  ...,  0.6133,  0.5898,  0.5742],
         [-0.1133, -0.1055, -0.1055,  ...,  0.5977,  0.5430,  0.4961]],

        [[-0.3711, -0.4102, -0.4492,  ..., -0.7461, -0.8477, -0.9102],
         [-0.4023, -0.4727, -0.5586,  ..., -0.5977, -0.6211, -0.6445],
         [-0.4961, -0.5273, -0.5664,  ..., -0.6055, -0.5742, -0.5586],
         ...,
         [-0.6055, -0.5820, -0.5586,  ...,  0.6133,  0.6133,  0.6211],
         [-0.6055, -0.5898, -0.5820,  ...,  0.6211,  0.5977,  0.5820],
         [-0.6055, -0.5977, -0.5977,  ...,  0.6055,  0.5508,  0.5039]],

        [[-0.4961, -0.5352, -0

Richard_Gere
Richard_Gere_0001.jpg
./faces/Richard_Gere\Richard_Gere_0001.jpg
tensor([[[ 0.1836,  0.1680,  0.1445,  ..., -0.3008, -0.3320, -0.3555],
         [ 0.1602,  0.1523,  0.1289,  ..., -0.3164, -0.3477, -0.3633],
         [ 0.1445,  0.1367,  0.1211,  ..., -0.3398, -0.3555, -0.3711],
         ...,
         [-0.8945, -0.8945, -0.8945,  ...,  0.3477,  0.3477,  0.3477],
         [-0.9102, -0.9102, -0.9023,  ...,  0.3633,  0.3633,  0.3633],
         [-0.9258, -0.9180, -0.9102,  ...,  0.3789,  0.3711,  0.3711]],

        [[ 0.1445,  0.1289,  0.1055,  ..., -0.3633, -0.3945, -0.4180],
         [ 0.1211,  0.1133,  0.0898,  ..., -0.3789, -0.4102, -0.4258],
         [ 0.1055,  0.0977,  0.0820,  ..., -0.4023, -0.4180, -0.4336],
         ...,
         [-0.9102, -0.9102, -0.9102,  ...,  0.0508,  0.0508,  0.0508],
         [-0.9258, -0.9258, -0.9180,  ...,  0.0664,  0.0664,  0.0664],
         [-0.9414, -0.9336, -0.9258,  ...,  0.0820,  0.0742,  0.0742]],

        [[-0.0898, -0.1055, -0.1289,  

Saddam_Hussein
Saddam_Hussein_0001.jpg
./faces/Saddam_Hussein\Saddam_Hussein_0001.jpg
tensor([[[ 0.5195,  0.5039,  0.4648,  ..., -0.7383, -0.7539, -0.7617],
         [ 0.5039,  0.4805,  0.4414,  ..., -0.7383, -0.7539, -0.7617],
         [ 0.4883,  0.4648,  0.4258,  ..., -0.7383, -0.7539, -0.7539],
         ...,
         [-0.8633, -0.8633, -0.8633,  ...,  0.6758,  0.7148,  0.7305],
         [-0.8633, -0.8633, -0.8633,  ...,  0.5898,  0.6289,  0.6523],
         [-0.8711, -0.8711, -0.8711,  ...,  0.4883,  0.5273,  0.5508]],

        [[ 0.6523,  0.6367,  0.5977,  ..., -0.7539, -0.7617, -0.7617],
         [ 0.6367,  0.6133,  0.5742,  ..., -0.7617, -0.7617, -0.7617],
         [ 0.6133,  0.5898,  0.5508,  ..., -0.7617, -0.7617, -0.7617],
         ...,
         [-0.8945, -0.8945, -0.8945,  ...,  0.7773,  0.8164,  0.8398],
         [-0.8945, -0.8945, -0.8945,  ...,  0.6836,  0.7227,  0.7461],
         [-0.9023, -0.9023, -0.9023,  ...,  0.5664,  0.6133,  0.6367]],

        [[ 0.7070,  0.6914,  0

Spencer_Abraham
Spencer_Abraham_0001.jpg
./faces/Spencer_Abraham\Spencer_Abraham_0001.jpg
tensor([[[-0.3164, -0.2930, -0.2461,  ..., -0.0508, -0.1133, -0.1445],
         [-0.3477, -0.3242, -0.2852,  ..., -0.1289, -0.1445, -0.1523],
         [-0.3789, -0.3555, -0.3164,  ..., -0.1914, -0.1680, -0.1523],
         ...,
         [ 0.4727,  0.4492,  0.3945,  ..., -0.5195, -0.5273, -0.5352],
         [ 0.4648,  0.4492,  0.4023,  ..., -0.5195, -0.5273, -0.5352],
         [ 0.4727,  0.4570,  0.4180,  ..., -0.5273, -0.5352, -0.5430]],

        [[-0.3320, -0.3086, -0.2695,  ..., -0.2227, -0.2695, -0.3008],
         [-0.3633, -0.3477, -0.3086,  ..., -0.3008, -0.3086, -0.3086],
         [-0.3945, -0.3789, -0.3398,  ..., -0.3633, -0.3320, -0.3086],
         ...,
         [ 0.6445,  0.6211,  0.5742,  ..., -0.6758, -0.6836, -0.6914],
         [ 0.6445,  0.6289,  0.5820,  ..., -0.6758, -0.6836, -0.6914],
         [ 0.6523,  0.6367,  0.5977,  ..., -0.6836, -0.6914, -0.6992]],

        [[-0.4258, -0.4023

Tommy_Thompson
Tommy_Thompson_0001.jpg
./faces/Tommy_Thompson\Tommy_Thompson_0001.jpg
tensor([[[ 0.7383,  0.7539,  0.7773,  ..., -0.6289, -0.6523, -0.6602],
         [ 0.7539,  0.7617,  0.7852,  ..., -0.6055, -0.6211, -0.6367],
         [ 0.7617,  0.7695,  0.7852,  ..., -0.5742, -0.5898, -0.6055],
         ...,
         [ 0.3398,  0.3398,  0.3320,  ...,  0.2148,  0.1914,  0.1836],
         [ 0.3398,  0.3398,  0.3320,  ...,  0.2148,  0.1914,  0.1836],
         [ 0.3398,  0.3398,  0.3320,  ...,  0.2148,  0.1914,  0.1836]],

        [[ 0.6758,  0.6914,  0.7148,  ..., -0.7539, -0.7773, -0.7930],
         [ 0.6914,  0.6992,  0.7227,  ..., -0.7227, -0.7539, -0.7695],
         [ 0.6992,  0.7070,  0.7227,  ..., -0.6914, -0.7227, -0.7383],
         ...,
         [ 0.3008,  0.3008,  0.2930,  ...,  0.0039, -0.0117, -0.0195],
         [ 0.3008,  0.3008,  0.2930,  ...,  0.0039, -0.0117, -0.0195],
         [ 0.3008,  0.3008,  0.2930,  ...,  0.0039, -0.0117, -0.0195]],

        [[ 0.3867,  0.4023,  0

Trent_Lott
Trent_Lott_0001.jpg
./faces/Trent_Lott\Trent_Lott_0001.jpg
tensor([[[-0.1992, -0.1914, -0.1836,  ..., -0.5977, -0.5742, -0.5586],
         [-0.2148, -0.2070, -0.1992,  ..., -0.5977, -0.5664, -0.5508],
         [-0.2305, -0.2305, -0.2227,  ..., -0.5977, -0.5664, -0.5508],
         ...,
         [ 0.8945,  0.8945,  0.8867,  ..., -0.5508, -0.5508, -0.5508],
         [ 0.8945,  0.8945,  0.8867,  ..., -0.5664, -0.5664, -0.5664],
         [ 0.9023,  0.9023,  0.8945,  ..., -0.5742, -0.5742, -0.5742]],

        [[-0.3789, -0.3711, -0.3633,  ..., -0.7773, -0.7539, -0.7383],
         [-0.3945, -0.3867, -0.3789,  ..., -0.7773, -0.7461, -0.7305],
         [-0.4023, -0.4023, -0.4023,  ..., -0.7695, -0.7383, -0.7227],
         ...,
         [ 0.6523,  0.6523,  0.6445,  ..., -0.7305, -0.7305, -0.7305],
         [ 0.6602,  0.6602,  0.6523,  ..., -0.7383, -0.7383, -0.7383],
         [ 0.6680,  0.6680,  0.6602,  ..., -0.7539, -0.7461, -0.7461]],

        [[-0.5039, -0.4961, -0.4883,  ..., -0.

Winona_Ryder
Winona_Ryder_0001.jpg
./faces/Winona_Ryder\Winona_Ryder_0001.jpg
tensor([[[-0.0352, -0.0117,  0.0273,  ..., -0.2617, -0.2695, -0.2773],
         [-0.0664, -0.0430, -0.0039,  ..., -0.2539, -0.2695, -0.2852],
         [-0.1055, -0.0742, -0.0273,  ..., -0.2539, -0.2695, -0.2852],
         ...,
         [ 0.0039,  0.0039,  0.0117,  ..., -0.4570, -0.4258, -0.4023],
         [ 0.0117,  0.0117,  0.0117,  ..., -0.4336, -0.3945, -0.3711],
         [ 0.0195,  0.0195,  0.0195,  ..., -0.4180, -0.3711, -0.3477]],

        [[-0.0273, -0.0039,  0.0352,  ..., -0.3789, -0.3789, -0.3789],
         [-0.0586, -0.0352,  0.0039,  ..., -0.3711, -0.3789, -0.3867],
         [-0.0977, -0.0664, -0.0195,  ..., -0.3633, -0.3789, -0.3867],
         ...,
         [-0.0117, -0.0117, -0.0039,  ..., -0.6055, -0.5742, -0.5508],
         [-0.0039, -0.0039, -0.0039,  ..., -0.5820, -0.5430, -0.5195],
         [ 0.0039,  0.0039,  0.0039,  ..., -0.5664, -0.5195, -0.4961]],

        [[-0.3555, -0.3242, -0.2773,  

In [19]:

# Example usage
import numpy as np
def recognize_face(test_image_path):
    try:
        # Load test image and process with MTCNN
        test_image = Image.open(test_image_path)
        print("Hello Opened")
        cropped_face = mtcnn(test_image)
        print("Hello Cropped")
        print(cropped_face)

        if cropped_face is None:
            
            print("No face detected in the image.")
            return

        # Generate embedding for the test image
        test_embedding = np.array(model(cropped_face.unsqueeze(0)).detach()).flatten()
        print("Hello Embedding generated")

        # Compare with known embeddings
        for person_name, known_embedding in known_embeddings.items():
            print("Hello Checking similarity")
            cosine_measure=cosine(test_embedding, np.array(known_embedding).flatten())
            print("Cosine measure found")
            similarity=1-cosine_measure
            print("Similarity checked")

            if similarity > threshold:
                print(f"Match found: {person_name} (Similarity: {similarity:.2f})")
                return

        print("No match found.")
    except Exception as e:
        print(f"Error processing test image: {e}")

# Example usage

test_image_path = r"C:\Users\PMLS\OneDrive - Higher Education Commission\Documents\University Work\Sixth Semester\Machine Learning\Assignments\Facenet assignment\faces\Abdullah_Gul\Abdullah_Gul_0014.jpg"  # Replace with the test image path
recognize_face(test_image_path)

Hello Opened
Hello Cropped
tensor([[[-0.7930, -0.8086, -0.8320,  ..., -0.7383, -0.7461, -0.7539],
         [-0.7930, -0.8086, -0.8320,  ..., -0.7148, -0.7227, -0.7305],
         [-0.8008, -0.8164, -0.8320,  ..., -0.6836, -0.6992, -0.7070],
         ...,
         [-0.6992, -0.7148, -0.7305,  ..., -0.4414, -0.5977, -0.6914],
         [-0.8008, -0.8086, -0.8164,  ..., -0.4492, -0.6055, -0.6914],
         [-0.8867, -0.8867, -0.8789,  ..., -0.4492, -0.5977, -0.6836]],

        [[-0.8945, -0.9023, -0.9180,  ..., -0.8008, -0.8164, -0.8242],
         [-0.8945, -0.9023, -0.9180,  ..., -0.7852, -0.7930, -0.8008],
         [-0.8945, -0.9023, -0.9180,  ..., -0.7617, -0.7695, -0.7773],
         ...,
         [-0.8008, -0.8086, -0.8242,  ..., -0.4961, -0.6602, -0.7461],
         [-0.8789, -0.8867, -0.8945,  ..., -0.5039, -0.6602, -0.7461],
         [-0.9492, -0.9492, -0.9492,  ..., -0.5039, -0.6523, -0.7383]],

        [[-0.9414, -0.9492, -0.9648,  ..., -0.8867, -0.8789, -0.8789],
         [-0.9414,

# Conclusion
* The results are comprehensibly correct. 
* Although we have generating embeddings for each person based on a single image which could result in bad representation issue and declined accuracy but the model was checked with 2 random images of 2 people and the results were accurate and the model was able to correctly identify the face.